### ISSUE TITLE
Exception when using with Spring, Gradle, Kotlin project

### ISSUE THREAD

**Issue by keesvandieren** [OSSIndex/ossindex-gradle-plugin#34]
Created Spring Boot project with Kotlin as language, Gradle build system.

Added last version of plugin

Run with: ./gradlew audit --info --stacktrace

Results in Exception:

    * What went wrong:
    Execution failed for task ':audit'.
    > net.jpountz.xxhash.StreamingXXHash32.<init>(I)V
    
    * Try:
    Run with --debug option to get more log output. Run with --scan to get full insights.
    
    * Exception is:
    org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':audit'.
            at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
            at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
            at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
            at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
            at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
            at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
            at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
            at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
            at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
            at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
            at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
            at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
            at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
            at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
            at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
            at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
            at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
            at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
            at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
            at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
            at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
            at org.gradle.execution.taskgraph.LocalTaskInfoExecutor.execute(LocalTaskInfoExecutor.java:42)
            at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:277)
            at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:262)
            at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:135)
            at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
            at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.execute(DefaultTaskPlanExecutor.java:200)
            at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:191)
            at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
            at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
            at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
            at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
    Caused by: java.lang.NoSuchMethodError: net.jpountz.xxhash.StreamingXXHash32.<init>(I)V
            at net.jpountz.xxhash.AbstractStreamingXXHash32Java.<init>(AbstractStreamingXXHash32Java.java:27)
            at net.jpountz.xxhash.StreamingXXHash32JavaSafe.<init>(StreamingXXHash32JavaSafe.java:27)
            at net.jpountz.xxhash.StreamingXXHash32JavaSafe$Factory.newStreamingHash(StreamingXXHash32JavaSafe.java:21)
            at net.jpountz.xxhash.XXHashFactory.newStreamingHash32(XXHashFactory.java:197)
            at net.jpountz.xxhash.XXHashFactory.<init>(XXHashFactory.java:168)
            at net.jpountz.xxhash.XXHashFactory.instance(XXHashFactory.java:47)
            at net.jpountz.xxhash.XXHashFactory.safeInstance(XXHashFactory.java:85)
            at net.jpountz.xxhash.XXHashFactory.fastestJavaInstance(XXHashFactory.java:111)
            at net.jpountz.xxhash.XXHashFactory.fastestInstance(XXHashFactory.java:137)
            at org.mapdb.CC.<clinit>(CC.java:47)
            at org.mapdb.serializer.SerializerByteArray.<clinit>(SerializerByteArray.java:15)
            at org.mapdb.Serializer.<clinit>(Serializer.java:315)
            at org.mapdb.DB.<clinit>(DB.kt:45)
            at org.mapdb.DBMaker$Maker.make(DBMaker.kt:477)
            at net.ossindex.common.request.PackageRequestService.run(PackageRequestService.java:183)
            at net.ossindex.gradle.audit.DependencyAuditor.runAudit(DependencyAuditor.java:118)
            at net.ossindex.gradle.OssIndexPlugin.doAudit(OssIndexPlugin.java:127)
            at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:801)
            at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:768)
            at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
            at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
            at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
            at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
            at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
            at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
            at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
            at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
            ... 31 more

Attached a demo project that reproduces the problem.

[demo 2.zip](https://github.com/OSSIndex/ossindex-gradle-plugin/files/2824347/demo.2.zip)

**Comment by ken-duck** [comment]
Thanks for the report and in particular the demo project. I have reproduced the problem with your example and am working on a fix.

**Comment by ken-duck** [comment]
There is a dependency collision between the version of Kotlin used by one of our dependencies (MapDB) with whatever happens in gradle when you are doing Kotlin builds. There are two possible fixes:

1. Shadow the MapDb dependency
2. Rewrite caching to not use MapDb

I am attempting the first, but it is giving me grief. I'll give it another week or so, but eventually I will give up and just rewrite caching (since I was planning on doing it anyhow). The problem is to rewrite caching the way I want will require a step-by-step rewrite of some other code and will take some time, which is why I am hoping to get option 1 working.

**Comment by ken-duck** [comment]
I believe that release 0.4.8 should solve your problem. If it does not please reopen the issue.

**Comment by keesvandieren** [comment]
Just verified, the new plugin works in our project (and found some vulnerabilities ;-)). 

Thanks for providing the plugin to the world 👍

**Comment by ken-duck** [comment]
Great to hear. Thanks for the feedback :)
