### ISSUE TITLE
"ConnectException: Server Error (500)" when OssIndexHttpClient makes POST request

### ISSUE THREAD

**Issue by wraschke** [OSSIndex/ossindex-gradle-plugin#41]
Hello, sorry in advance if this is the not correct org and repo to open this in.

Our builds use the Gradle OSSIndex plugins to scan for vulnerabilities.

Often this scan is successful and there are no problems. Yet lately, though intermittent but frequently, the builds run into this:

`Caused by: java.net.ConnectException: Server Error (500) at net.ossindex.common.request.OssIndexHttpClient.performPostRequest(OssIndexHttpClient.java:122) at net.ossindex.common.request.PackageRequest.run(PackageRequest.java:121) at net.ossindex.gradle.audit.DependencyAuditor.runAudit(DependencyAuditor.java:69)`

The problem occurs using version 5.1.1 of the the Gradle plugin. The OSSIndex plugin version is 0.3.8-beta. This has been working for us for a while, and just within the last week or so we started seeing this problem.

Full exception stack is at https://gist.github.com/wraschke/84a80af92ed7136fab624b8467a8263e.

There isn't more information from the server other than this status code.

The source for the plugin class making POST request appears to be at https://github.com/OSSIndex/java-api/blob/master/src/main/java/net/ossindex/common/request/OssIndexHttpClient.java. I'm presuming the POST request is being made to https://ossindex.sonatype.org/v2.0/

**Comment by ken-duck** [comment]
You found the right place :)

Thanks for the information. I will see what I can do.

**Comment by ken-duck** [comment]
Hi.

First thing you will want to do is upgrade to the newest version of the plugin (4.0.11). There are a great many improvements, including the underlying rest code. In fact there is a new database that this new API accesses which knows about even more vulnerabilities, so it is definitely the place to be.

**Comment by ken-duck** [comment]
Actually, I need to shut down the old API to make sure that everyone upgrades to the new database. Let me know when you are using the new version and I will shut down the old one.

**Comment by tevans78** [comment]
@ken-duck we moved our integration branch up to 4.0.11 this morning. Hopefully it won't take too long to get into master. However, we may also need to update some service branches and that may take us a bit more time. Please let us know if there is any kind of deadline for the old api?

**Comment by ken-duck** [comment]
I'll try and keep it up for a couple more weeks. It seems that something is going somewhat wrong there (hence the original problem). I have some suspicion that it might be getting "abused" as that API is running into resource limits that never used to be a factor (the new API is not running into the same problems).

If you need longer let me know and I will see what I can do. It will likely be unstable and unpredictable, though, depending on the load.

**Comment by wraschke** [comment]
Hi, @ken-duck , happily I haven't seen this since we upgraded the OSSIndex plugin to 0.4.11. Hope we can keep this open for...a week more?

**Comment by ken-duck** [comment]
Yup. I'm fine with that.

Its great to hear that it is working :)
